import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css"
import { AuthProvider } from "@/store/AuthContext";
import Header from '@/components/Header';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en">
      <body>
        <div className="flex flex-col">

        
        <Header />
        {children}
        </div>
      </body>
    </html>
    </AuthProvider>
  );
}
